# name: Immich
# description: High performance self-hosted photo and video management solution
# category: Media
# icon: photo_library
# version: 1.95.1
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION:-./data/immich/upload}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE_NAME=${DB_NAME:-immich}
      - REDIS_HOSTNAME=immich-redis
    ports:
      - ${IMMICH_PORT:-2283}:2283
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE_NAME=${DB_NAME:-immich}
      - REDIS_HOSTNAME=immich-redis
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine
    restart: always

  immich-postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_DB=${DB_NAME:-immich}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ${DB_DATA_LOCATION:-./data/immich/db}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
