# name: Tailscale
# description: The private WireGuard VPN mesh network that connects all your devices.
# category: Network
# icon: settings_ethernet
# version: 1.66.0
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: host
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - ${TAILSCALE_STATE_PATH:-./data/tailscale/state}:/var/lib/tailscale
      - /var/run/tailscale:/var/run/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
